version: '3.8'

services:
  redis:
    image: redislabs/rejson:latest
    container_name: shapley-redisjson
    ports:
      - "6379:6379"
    volumes:
      - rejson_data:/data
    networks:
      - shapley-network

volumes:
  rejson_data:

networks:
  shapley-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.20.0/24
          gateway: 192.168.20.1

